name: tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/requirements.txt', '**/requirements_minimal.txt', 'setup.py', '.github/workflows/*') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python3 -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run separation test
        run: make test_eval
